

import type { Metadata } from 'next'
import { Nunito, Dancing_Script } from 'next/font/google'
import { Providers } from './providers'
import "./reset.css"
import "./global.css"
import Header from '@/components/Header/Header'

const nunito = Nunito({ subsets: ['latin'] })
export const DancingScript = Dancing_Script({ subsets: ['latin'], weight:'700' })
// export const
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body style={nunito.style}>
                <Providers>
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    )
}
